version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: FirstPostgressDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  api:
    build:
      context: .
    container_name: clean-arch-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=FirstPostgressDB;Username=postgres;Password=password
    ports:
      - "5000:80"
    depends_on:
      - db
