# Use the official .NET Core SDK image to build the application
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

# Use the official .NET SDK image to build and publish the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["CleanArchitectureDemo.API/CleanArchitectureDemo.API.csproj", "CleanArchitectureDemo.API/"]
RUN dotnet restore "CleanArchitectureDemo.API/CleanArchitectureDemo.API.csproj"
COPY . .
WORKDIR "/src/CleanArchitectureDemo.API"
RUN dotnet build "CleanArchitectureDemo.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CleanArchitectureDemo.API.csproj" -c Release -o /app/publish

# Copy the published output to the base image and define the entry point
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CleanArchitectureDemo.API.dll"]
